package:
  name: hello-server
  version: 0.1.0
  epoch: 0
  description: friendly little webserver
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - busybox
      - git
      - go
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/maligin/partner-enablement-workshop/archive/refs/heads/main.tar.gz
      expected-sha256: f249e17d5078aa2198a9129f06115f65ed5b44e391aff7062e129da4a0498aea
  - name: Build Go application
    runs: |
      CGO_ENABLED=0 go build -o "${{targets.destdir}}/usr/bin/hello-server" .
