package:
  name: hello-server
  version: 0.1.0
  epoch: 0
  description: friendly little webserver
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - busybox
      - git
      - go
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/maligin/partner-enablement-workshop/archive/refs/heads/main.tar.gz
      expected-sha256: ce03e2a085d49050cc3d890ecef276566724f8b6119d824d657a8e6baeafe22b
  - name: Build Go application
    runs: |
      CGO_ENABLED=0 go build -o "${{targets.destdir}}/usr/bin/hello-server" .
